version: "3"
services:
 web:
  build: ./verificationServer
  container_name: blockchain_web
  volumes:
    - ~/Documents/DockerVolumes/TheOol/Blockchain/verificationServer:/usr/src/app
  restart: always
  ports:
    - 80:5000
  working_dir: /usr/src/app
  command: python app.py
 db:
  image: mysql
  container_name: blockchain_db
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: 123456
 adminer:
  image: adminer
  container_name: blockchain_db_adminer
  restart: always
  ports:
    - 6080:8080