version: "3"
services:
 web:
  build: ./server
  container_name: blockchain_web
  volumes:
    - ~/Documents/DockerVolumes/TheOol/Blockchain/server:/usr/src/app
  restart: always
  ports:
    - 80:5000
  working_dir: /usr/src/app
  command: python app.py
 db:
  image: mariadb
  container_name: blockchain_db
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: 123456
 adminer:
  image: adminer
  container_name: blockchain_db_adminer
  restart: always
  ports:
    - 6080:8080