version: "3"
services:
 ver_server:
  build: ./verificationServer
  container_name: ver_server
  volumes:
    - ./verificationServer:/usr/src/app
    - ./consensus/BlockChain/block:/var/blocks
  environment:
    PYTHONDONTWRITEBYTECODE: 1
    CON_SERVER_IP: ${CON_SERVER_IP:-consensus}
  restart: always
  ports:
    - 80:5000
  working_dir: /usr/src/app
  command: python app.py
  links:
    - "db"

 consensus:
  build: ./consensus
  container_name: consensus
  volumes:
    - ./consensus:/usr/src/app
  environment:
    PYTHONDONTWRITEBYTECODE: 1
  restart: always
  ports:
    - 9090:9090
  working_dir: /usr/src/app
  command: python app.py

 db:
  image: mysql
  container_name: db
  command: --default-authentication-plugin=mysql_native_password
  volumes:
    - mysql:/var/lib/mysql
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123123}
  cap_add:
      - SYS_NICE
 adminer:
  image: adminer
  container_name: blockchain_db_adminer
  restart: always
  ports:
    - 6080:8080
  links:
    - "db"
 ver_db:
  build: ./ver_db
  container_name: ver_db
  command: --default-authentication-plugin=mysql_native_password
  volumes:
    - ./ver_db/:/var/spool/cron/crontabs/
    - ./ver_db/data:/home/data
    - ver_mysql:/var/lib/mysql
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: ${VER_MYSQL_ROOT_PASSWORD:-123123}
  cap_add:
      - SYS_NICE
volumes:
  mysql:
    driver: local
  ver_mysql:
    driver: local