version: "3"
services:
 web:
  build: ./verificationServer
  container_name: blockchain_web
  volumes:
    - ${VOLUME_DIR}/verificationServer:/usr/src/app
  environment:
    PYTHONDONTWRITEBYTECODE: 1
  restart: always
  ports:
    - 80:5000
  working_dir: /usr/src/app
  command: python app.py
  links:
    - "db"
 db:
  image: mysql
  container_name: blockchain_db
  command: --default-authentication-plugin=mysql_native_password
  volumes:
    - mysql:/var/lib/mysql
  restart: always
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  cap_add:
      - SYS_NICE
 adminer:
  image: adminer
  container_name: blockchain_db_adminer
  restart: always
  ports:
    - 6080:8080
  links:
    - "db"
volumes:
  mysql:
    driver: local